services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3001:8080"
    volumes:
      - ${DATA_PATH}:/app/backend/data
      - ./ssl/cert.pem:/app/cert.pem
      - ./ssl/key.pem:/app/key.pem
    env_file:
      - ./open-webui.env
    environment:
      - AUTOMATIC1111_BASE_URL=http://localhost:7860/
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_MODEL=v1-5-pruned-emaonly
      - IMAGE_SIZE=640x800
      - ENABLE_NOTES=true
      - ENABLE_MEMORIES=true
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./ssl/cert.pem:/cert.pem
      - ./ssl/key.pem:/key.pem
    depends_on:
      - open-webui
    restart: unless-stopped

  kokoro-web:
    image: ghcr.io/eduardolat/kokoro-web:latest
    ports:
      - "3000:3000"
    env_file:
      - ./kokoro.env
    volumes:
      - ./kokoro-cache:/kokoro/cache
    restart: unless-stopped

volumes:
  open-webui-data:

# Ensure services are on the same network 
networks:
  default:
    driver: bridge
